version: "2"
services:
  base:
    image: mic92/sharelatex-base
    build:
      context: base
    command: /bin/true
  nodejs:
    image: mic92/sharelatex-nodejs
    build:
      context: nodejs
    command: /bin/true
    depends_on:
      - base
  redis:
    image: mic92/sharelatex-redis
    build:
      context: redis
    depends_on:
      - base
    volumes:
      - dataredis:/data
  docstore:
    # image: mic92/sharelatex-docstore
    image: jzeng9/sharelatex:latest
    build:
      context: docstore
    links:
      - mongodb
    depends_on:
      - nodejs
  mongodb:
    image: mic92/sharelatex-mongodb
    build:
      context: mongodb
    depends_on:
      - base
    volumes:
      - datamongodb:/data/db
  postgresql:
    image: mic92/sharelatex-postgresql
    build:
      context: postgresql
    depends_on:
      - base
    volumes:
      - datapostgresql:/var/lib/postgresql/data
  influxdb:
    image: mic92/sharelatex-influxdb
    build:
      context: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    depends_on:
      - base
    volumes:
      - datainfluxdb:/data
volumes:
    dataredis:
      driver: local
    datamongodb:
      driver: local
    datapostgresql:
      driver: local
    datainfluxdb:
      driver: local
