version: "2"
services:
  base:
    image: mic92/sharelatex-base
    build:
      context: base
    command: /bin/true
    networks:
      envoymesh:
        aliases:
          - base
    # logging:
    #   driver: none
  nodejs:
    image: mic92/sharelatex-nodejs
    build:
      context: nodejs
    command: /bin/true
    depends_on:
      - base
    networks:
      envoymesh:
        aliases:
          - nodejs
    # logging:
    #   driver: none
  redis:
    image: mic92/sharelatex-redis
    build:
      context: redis
    depends_on:
      - base
    volumes:
      - dataredis:/data
    networks:
      envoymesh:
        aliases:
          - redis
    # logging:
      # driver: none
  docstore:
    # image: mic92/sharelatex-docstore
    image: jzeng9/sharelatex:latest
    build:
      context: docstore
    links:
      - mongodb
    depends_on:
      - nodejs
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    networks:
      envoymesh:
        aliases:
          - docstore
    # logging:
      # driver: none
  
  prod-envoy-proxy:
    image: csci2952fmicrocow/prod-storage-envoy:latest
    build:
      context: prod-envoy
      # dockerfile: Dockerfile
      # volumes:
      # - ./prod-envoy.yaml:/etc/envoy.yaml
    # depends_on:
      # - docstore
    networks:
      envoymesh:
        aliases:
          - prod-envoy-proxy
    expose:
      - "9999"
      - "9901"
    # logging:
      # driver: none

  mongodb:
    image: mic92/sharelatex-mongodb
    build:
      context: mongodb
    depends_on:
      - base
    volumes:
      - datamongodb:/data/db
    networks:
      envoymesh:
        aliases:
          - mongodb
    # logging:
      # driver: none

  postgresql:
    image: mic92/sharelatex-postgresql
    build:
      context: postgresql
    depends_on:
      - base
    volumes:
      - datapostgresql:/var/lib/postgresql/data
    networks:
      envoymesh:
        aliases:
          - postgresql
    # logging:
      # driver: none

  influxdb:
    image: mic92/sharelatex-influxdb
    build:
      context: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    depends_on:
      - base
    volumes:
      - datainfluxdb:/data
    networks:
      envoymesh:
        aliases:
          - influxdb
    # logging:
      # driver: none
volumes:
    dataredis:
      driver: local
    datamongodb:
      driver: local
    datapostgresql:
      driver: local
    datainfluxdb:
      driver: local

networks:
  envoymesh: {}
