version: "2"
services:
  base:
    image: mic92/sharelatex-base
    build:
      context: base
    command: /bin/true
    networks:
      envoymesh:
        aliases:
          - base
    logging:
      driver: none
  nodejs:
    image: mic92/sharelatex-nodejs
    build:
      context: nodejs
    command: /bin/true
    depends_on:
      - base
    networks:
      envoymesh:
        aliases:
          - nodejs
    logging:
      driver: none
  redis:
    image: mic92/sharelatex-redis
    build:
      context: redis
    depends_on:
      - base
    volumes:
      - dataredis:/data
    networks:
      envoymesh:
        aliases:
          - redis
    logging:
      driver: none
  docstore:
    image: jzeng9/sharelatex:latest
    build:
      context: docstore
    links:
      - mongodb
    depends_on:
      - nodejs
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    networks:
      envoymesh:
        aliases:
          - docstore
    # logging:
    #   driver: none
  test-docstore:
    image: jzeng9/sharelatex-test
    build:
      context: docstore
    links:
      - test-mongodb
    depends_on:
      - nodejs
    expose:
      - "3000"
    # ports:
    #   - "3001:3000"
    networks:
      envoymesh:
        aliases:
          - test-docstore
    # logging:
    #   driver: none
  prod-envoy-proxy:
    image: csci2952fmicrocow/prod-storage-envoy:latest
    build:
      context: prod-envoy
    volumes:
      - ./prod-envoy.yaml:/dosa_server.yaml
      - ./test-script-from-prod-envoy.py:/home/test-script-from-prod-envoy.py
    networks:
      envoymesh:
        aliases:
          - prod-envoy-proxy
    expose:
      - "9999"
      - "9901"
    # logging:
    #   driver: none

  test-storage-envoy-proxy:
    image: csci2952fmicrocow/test-storage-envoy:latest
    build:
      context: prod-envoy
    volumes:
      - ./test-storage-envoy.yaml:/dosa_server.yaml
    networks:
      envoymesh:
        aliases:
          - test-storage-envoy-proxy
    expose:
      - "9999"
      - "9901"
    # logging:
    #   driver: none

  test-service-envoy-proxy:
    image: csci2952fmicrocow/test-service-enovy:latest
    build:
      context: prod-envoy
    volumes:
      - ./test-service-envoy.yaml:/dosa_server.yaml
    networks:
      envoymesh:
        aliases:
          - test-service-envoy-proxy
    expose:
      - "9999"
      - "9901"
    # logging:
    #   driver: none

  mongodb:
    image: mic92/sharelatex-mongodb
    build:
      context: mongodb
    depends_on:
      - base
    volumes:
      - datamongodb:/data/db
    networks:
      envoymesh:
        aliases:
          - mongodb
    # logging:
    #   driver: none
  test-mongodb:
    image: mic92/sharelatex-mongodb
    build:
      context: mongodb
    depends_on:
      - base
    volumes:
      - testdatamongodb:/data/db
    networks:
      envoymesh:
        aliases:
          - test-mongodb
    # logging:
    #   driver: none
volumes:
  dataredis:
    driver: local
  datamongodb:
    driver: local
  testdatamongodb:
    driver: local

networks:
  envoymesh: {}
