version: "2"
services:
  base:
    image: mic92/sharelatex-base
    build:
      context: base
    command: /bin/true
    networks:
      envoymesh:
        aliases:
          - base
  nodejs:
    image: mic92/sharelatex-nodejs
    build:
      context: nodejs
    command: /bin/true
    depends_on:
      - base
    networks:
      envoymesh:
        aliases:
          - nodejs
  redis:
    image: mic92/sharelatex-redis
    build:
      context: redis
    depends_on:
      - base
    volumes:
      - dataredis:/data
    networks:
      envoymesh:
        aliases:
          - redis
  docstore:
    # image: mic92/sharelatex-docstore
    image: jzeng9/sharelatex:latest
    build:
      context: docstore
    links:
      - mongodb
    depends_on:
      - nodejs
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    networks:
      envoymesh:
        aliases:
          - docstore
  
  prod-envoy-proxy:
    build:
      context: .
      dockerfile: Dockerfile-prod-envoy
    volumes:
      - ./prod-envoy.yaml:/etc/envoy.yaml
    depends_on:
      - docstore
    networks:
      envoymesh:
        aliases:
          - prod-envoy-proxy
    expose:
      - "9999"
      - "9901"

  mongodb:
    image: mic92/sharelatex-mongodb
    build:
      context: mongodb
    depends_on:
      - base
    volumes:
      - datamongodb:/data/db
    networks:
      envoymesh:
        aliases:
          - mongodb

  postgresql:
    image: mic92/sharelatex-postgresql
    build:
      context: postgresql
    depends_on:
      - base
    volumes:
      - datapostgresql:/var/lib/postgresql/data
    networks:
      envoymesh:
        aliases:
          - postgresql
  influxdb:
    image: mic92/sharelatex-influxdb
    build:
      context: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    depends_on:
      - base
    volumes:
      - datainfluxdb:/data
    networks:
      envoymesh:
        aliases:
          - influxdb
volumes:
    dataredis:
      driver: local
    datamongodb:
      driver: local
    datapostgresql:
      driver: local
    datainfluxdb:
      driver: local

networks:
  envoymesh: {}
