admin:
  access_log_path: /dev/null
  profile_path: "{{ test_tmpdir }}/envoy.prof"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  clusters:
    name: cluster_0
    connect_timeout: 0.25s
    type: logical_dns
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: docstore
                    port_value: 3000
  listeners:
    name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 9999
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: cluster_0 }
          http_filters:
            - name: dosa
              config:
                # cluster: test
                cluster: cluster_0
            - name: envoy.filters.http.router