#!/bin/bash

. /etc/default/grafana-server
if [ $# -lt 1 ]; then
  gosu grafana /usr/sbin/grafana-server                \
                    --config=${CONF_FILE}              \
                    --pidfile=${PID_FILE}              \
                    cfg:default.paths.logs=${LOG_DIR}  \
                    cfg:default.paths.data=${DATA_DIR} \
                    cfg:default.paths.plugins=${PLUGINS_DIR}
else
  exec "$@"
fi
